[GoldenDict]
web = "http://goldendict.org/"
platforms = [ "Linux", "Windows",]
license = "GPL"

[StarDict]
web = "http://huzheng.org/stardict/"
platforms = [ "Linux", "Windows", "Mac",]
license = "GPL"

["GoldenDict Mobile (Free)"]
web = "http://goldendict.mobi/"
# https://play.google.com/store/apps/details?id=mobi.goldendict.android.free
platforms = [ "Android",]
license = "Freeware"

["GoldenDict Mobile (Full)"]
web = "http://goldendict.mobi/"
# https://play.google.com/store/apps/details?id=mobi.goldendict.android
platforms = [ "Android",]
license = "Proprietary"

["Twinkle Star Dictionary"]
web = "https://play.google.com/store/apps/details?id=com.qtier.dict"
platforms = [ "Android",]
license = "Unknown"
# last release: 2015/10/19
# could not find the source code, license or website

[WordMateX]
web = "https://apkcombo.com/wordmatex/org.d1scw0rld.wordmatex/"
platforms = [ "Android",]
license = "Proprietary"
# last release: 2020/01/01, version 2.1.1
# Google Play says "not compatible with your devices", not letting me
# download and install, so I downloaded apk from apkcombo.com
# This is the only Android app (not just for StarDict format) I found
# that supports auto-RTL

[QDict]
web = "https://play.google.com/store/apps/details?id=com.annie.dictionary"
source = "https://github.com/namndev/QDict"
platforms = [ "Android",]
license = "Apache 2.0"
# last release: 2017/04/16 (keeps crashing on my device, unusable)
# last commit: 2020/06/24

["Fora Dictionary"]
web = "https://play.google.com/store/apps/details?id=com.ngc.fora"
platforms = [ "Android",]
license = "Proprietary"
# no dark mode
# some options show "Premium Feature"
# has prefix-search-on-type but it's a little slow
# supports RTL (haven't tested auto-RTL)

["Fora Dictionary Pro"]
web = "https://play.google.com/store/apps/details?id=com.ngc.fora.android"
platforms = [ "Android",]
license = "Proprietary"
