[GoldenDict]
web = "http://goldendict.org/"
platforms = [ "Linux", "Windows",]
license = "GPL"

[QTranslate]
web = "https://quest-app.appspot.com/"
platforms = [ "Windows",]
license = "Proprietary"

[Alpus]
web = "https://alpusapp.com/"
platforms = [ "Windows", "Mac", "Linux", "Android",]
license = "Freeware"
# Java-based
